export const selectOptions = [
  { value: 'site1', label: 'Field Station' },
  { value: 'site2', label: 'DFG Hill' },
  { value: 'site3', label: 'Buoy Repeater' },
  { value: 'site4', label: 'Far Hill' },
  { value: 'site5', label: 'Decker Pond' },
  { value: 'site6', label: 'BLM Burn Hill' },
  { value: 'site7', label: 'Far Pond' },
  { value: 'site8', label: 'Fordyce Repeater' },
  { value: 'site9', label: 'Fordyce Pond' },
  /*{ value: 10, label: 'Dan\'s Repeater' },
  { value: 11, label: 'Dan\'s Pond' },
  { value: 12, label: 'Red House' },
  { value: 13, label: 'Blue Oak Tower' },
  { value: 14, label: 'West Ashley' },
  { value: 15, label: 'Tip' },
  { value: 16, label: 'Wragg West' },
  { value: 17, label: 'Wragg East' },
  { value: 18, label: 'East Ashley' },
  { value: 20, label: 'Welborn' },
  { value: 21, label: 'QRWC Tower' },
  { value: 22, label: 'Weaver Tower' },
  { value: 23, label: 'Decker Buoy' },
  { value: 24, label: 'Reis' },
  { value: 25, label: 'Burn West' },
  { value: 26, label: 'Trailer' },
  { value: 27, label: 'Far Chamise' },
  { value: 28, label: 'PG&E' },
  { value: 29, label: 'East Connection' },
  { value: 30, label: 'Big Hill' },
  { value: 31, label: 'Fire Break' },
  { value: 32, label: 'BLM South' },
  { value: 33, label: 'Pine Ridge' },
  { value: 34, label: 'QR House' },
  { value: 35, label: 'Decker Canyon' },
  { value: 36, label: 'Shane\'s Repeater' },
  { value: 37, label: 'Shane\'s House' },
  { value: 38, label: 'Shane\'s Garage' },
  { value: 39, label: 'QR Studio' },
  { value: 40, label: 'Karen\'s Repeater' },
  { value: 41, label: 'Lab Trailer' },
  { value: 42, label: 'K1' },
  { value: 43, label: 'K2' },
  { value: 44, label: 'MB1' },
  { value: 45, label: 'MB2' },
  { value: 46, label: 'Scribner Gate' },*/
];