export const selectOptions = [
  { value: 'Field Station', label: 'Field Station' },
  { value: 'DFG Hill', label: 'DFG Hill' },
  { value: 'Buoy Repeater', label: 'Buoy Repeater' },
  { value: 'Far Hill', label: 'Far Hill' },
  { value: 'Decker Pond', label: 'Decker Pond' },
  { value: 'BLM Burn Hill', label: 'BLM Burn Hill' },
  { value: 'Far Pond', label: 'Far Pond' },
  { value: 'Fordyce Repeater', label: 'Fordyce Repeater' },
  { value: 'Fordyce Pond', label: 'Fordyce Pond' },
  { value: 'Dan\'s Repeater', label: 'Dan\'s Repeater' },
  { value: 'Dan\'s Pond', label: 'Dan\'s Pond' },
  { value: 'Red House', label: 'Red House' },
  { value: 'Blue Oak Tower', label: 'Blue Oak Tower' },
  { value: 'West Ashley', label: 'West Ashley' },
  { value: 'Tip', label: 'Tip' },
  { value: 'Wragg West', label: 'Wragg West' },
  { value: 'Wragg East', label: 'Wragg East' },
  { value: 'East Ashley', label: 'East Ashley' },
  { value: 'Welborn', label: 'Welborn' },
  { value: 'QRWC Tower', label: 'QRWC Tower' },
  { value: 'Weaver Tower', label: 'Weaver Tower' },
  { value: 'Decker Buoy', label: 'Decker Buoy' },
  { value: 'Reis', label: 'Reis' },
  { value: 'Burn West', label: 'Burn West' },
  { value: 'Trailer', label: 'Trailer' },
  { value: 'Far Chamise', label: 'Far Chamise' },
  { value: 'PG&E', label: 'PG&E' },
  { value: 'East Connection', label: 'East Connection' },
  { value: 'Big Hill', label: 'Big Hill' },
  { value: 'Fire Break', label: 'Fire Break' },
  { value: 'BLM South', label: 'BLM South' },
  { value: 'Pine Ridge', label: 'Pine Ridge' },
  { value: 'QR House', label: 'QR House' },
  { value: 'Decker Canyon', label: 'Decker Canyon' },
  { value: 'Shane\'s Repeater', label: 'Shane\'s Repeater' },
  { value: 'Shane\'s House', label: 'Shane\'s House' },
  { value: 'Shane\'s Garage', label: 'Shane\'s Garage' },
  { value: 'QR Studio', label: 'QR Studio' },
  { value: 'Karen\'s Repeater', label: 'Karen\'s Repeater' },
  { value: 'Lab Trailer', label: 'Lab Trailer' },
  { value: 'K1', label: 'K1' },
  { value: 'K2', label: 'K2' },
  { value: 'MB1', label: 'MB1' },
  { value: 'MB2', label: 'MB2' },
  { value: 'Scribner Gate', label: 'Scribner Gate' },
];